spring.application.name=student-clubs-system-client
server.port=8081

app.api.base-url=${APP_API_BASE_URL:http://localhost:8080}

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

spring.web.resources.static-locations=classpath:/static/

spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

logging.level.org.springframework.security=DEBUG
